name: Check for Broken Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Roz raat 12 baje chalega

jobs:
  link-check:
    name: Run Lychee link checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lychee link checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress ./README.md